POST https://postercolo.synology.me/auth/login
Content-Type: application/json

{
  "email": "postercolo@gmail.com",
  "password": "1234"
}

###
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "email": "postercolo@gmail.com",
  "password": "1234"
}